import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/global.scss";
import SpaceCanvas from "./component/SpaceCanvas";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/images/navigationBar/profile.png",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SpaceCanvas />
        {children}
      </body>
    </html>
  );
}
